### ISSUE TITLE
AttributeError: 'DataUpdateCoordinator' object has no attribute 'tank_id'

### ISSUE THREAD

**Issue by dandwhelan** [tomasmcguinness/homeassistant-mixergy#1]
I've tried adding and removing this integration multiple times, but I get this error each time. 

Could you please fix this or assist me on how I can resolve this myself? 

Logger: homeassistant.components.sensor
Source: custom_components/mixergy/sensor.py:297
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 7 August 2022 at 22:22:23 (5 occurrences)
Last logged: 11:50:08

Error while setting up mixergy platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mixergy/sensor.py", line 41, in async_setup_entry
    new_entities.append(EnergySensor(coordinator))
  File "/config/custom_components/mixergy/sensor.py", line 297, in __init__
    unique_id=f"mixergy_{tank.tank_id}_energy"
AttributeError: 'DataUpdateCoordinator' object has no attribute 'tank_id'

**Comment by tomasmcguinness** [comment]
Hi,

I haven't seen this before. Are you installing manually or using HACS?

**Comment by dandwhelan** [comment]
> Hi,
> 
> I haven't seen this before. Are you installing manually or using HACS?

Hi Tom, I've used the HACS using a custom repo. Shall I try the manual way?

**Comment by tomasmcguinness** [comment]
It's the same code, I just wanted to make sure you were using the most up-to-date version.

I've had a look and found what I think is the issue! I've pushed a small commit. I've created a new release v0.0.5, which should fix the issue.

**Comment by dandwhelan** [comment]
Fantastic. thanks for looking at it so quickly! Looking forward to trying
it out.

**Comment by dandwhelan** [comment]
Works perfectly :)

**Comment by tomasmcguinness** [comment]
Great! 

If you have any suggestions for things you'd like to see, I'd love to hear them.

How are you finding the Mixergy tank overall?

**Comment by dandwhelan** [comment]
I've recently got Solar and will be using excess Solar to dump some charge
into the hot water tank. I'm looking at finding a way to report tank %
charged without indirect or direct electricity (as solar doesn't show as
many).

Overall I think the Mixergy is great, it's made a dumb home appliance
rather smart.
