### ISSUE TITLE
sensor.mixergy_electric_heat_energy unexpected device class

### ISSUE THREAD

**Issue by reedy** [tomasmcguinness/homeassistant-mixergy#21]
I added `sensor.mixergy_electric_heat_energy` to `Individual devices` on a day the mixergy had used electricity itself.. It showed fine in the graph.

After midnight, and before any electricity had been used, it was the showing as:

![Screenshot 2023-10-12 at 00 56 32](https://github.com/tomasmcguinness/homeassistant-mixergy/assets/67615/675d4648-06af-433b-bc9d-bc1637fd1b29)

**Comment by reedy** [comment]
I'm not using it for anything specifically (other than in this case), mostly just keeping track/for awareness of energy usage of a few high energy usage devices.

So yeah, mostly a case of it shouldn't probably happen :)

**Comment by reedy** [comment]
It seems (checking again, just before midnight) it's.. still showing like that.

It's showing energy used correctly on "Monitor individual devices" though for the Mixergy...

**Comment by tomasmcguinness** [comment]
I'm going to close this ticket. Some changes were made this entity a few versions ago and I haven't had anyone else report the issue.

If you're still experiencing a problem, let me know!
