### ISSUE TITLE
Can’t see ‘Set Charge’ option

### ISSUE THREAD

**Issue by hogsterbogster** [tomasmcguinness/homeassistant-mixergy#24]
Hi there,

Please forgive the newbie question, I’m very new to HA.

I’d like to add a slider that will allow me to set the tank to charge to a preset level, and it seems this functionality is supported with the service “mixergy.mixergy_set_charge” … but when I try and add an Entity with this name it doesn’t appear in the list — please see attached screenshot.

What am I doing wrong and how to I add a slider that will allow me to request the tank to charge to a certain percentage?

Many thanks for your help!

David ☺️

![IMG_0020](https://github.com/tomasmcguinness/homeassistant-mixergy/assets/149208922/46762e70-5c86-40ec-91dc-33cfa7fba48e)

**Comment by hogsterbogster** [comment]
Got it working with some help!

For those who might wonder how to do this in the future, this is how I did it:

Under Settings -> Devices & Services -> Helpers, created the following 'Number' Helper:

![Screenshot 2023-10-30 at 17 43 03](https://github.com/tomasmcguinness/homeassistant-mixergy/assets/149208922/0d6fe9e3-6ab0-4b45-940c-42dc6022e3bf)

Then under Settings -> Automations & Scenes -> Automations, created the following Automation:

![Screenshot 2023-10-30 at 17 45 04](https://github.com/tomasmcguinness/homeassistant-mixergy/assets/149208922/a5a716b4-62ce-4a15-be3d-c6010fbf0e21)

Then finally in the Dashboard editor, I created the following Entities Card:
 
![Screenshot 2023-10-30 at 17 44 02](https://github.com/tomasmcguinness/homeassistant-mixergy/assets/149208922/c3e00cbb-3204-4f80-82a0-6397762ed839)

Very satisfying! 😁

**Comment by tomasmcguinness** [comment]
That's excellent!
