### ISSUE TITLE
Allow device to be visible in HomeKit

### ISSUE THREAD

**Issue by crisp82** [tomasmcguinness/homeassistant-mixergy#26]
Hi there,

Would it be possible to surface the device through HomeKit and  control actions from there (I.e., set holiday mode, change target temperature, boost to x % (multiples of 10)?

Regards,

Crisp82

**Comment by tomasmcguinness** [comment]
Hi. 

You should be able to surface some of these switches and controls via Homekit using home assistant already, but I don't know how easy that would be to achieve.

**Comment by crisp82** [comment]
I believe I can surface the sensors, but I am not sure how to combine them as a single entity with multiple properties and actions.

I will keep digging…

**Comment by crisp82** [comment]
Hi,

I am very new to this all, but my testing so far shows that what I am thinking of is have an entity that would be presented to HomeKit that could make the service call will not work.

However, I use the BlueAir integration: https://github.com/aijayadams/hass-blueair, which works in the following way:

1. Query cloud portal for air purifier devices
2. Create devices within HomeAssistant. These controls act as an on/off condition with the ability to set ‘fan speed’ as a %.

I would see this as what I am trying to achieve - have a Mixergy cylinder appear in HomeKit with the ability to set a %.

The only change to this would be that it would be good to see the existing current_charge sensor.
 
Do you think this would be possible in your integration?

**Comment by tomasmcguinness** [comment]
If you can create an artificial HomeKit entity, you could use the current_change to give you a percentage. As for setting a fan speed, you could pass that value into the set_current_change service. 

I've just never seen the need since the Mixergy app is also installed on my phone.

Curious to know if you've made this work at all.

**Comment by tomasmcguinness** [comment]
Closing this due as it's stale. Please reopen if necessary.
