### ISSUE TITLE
Feature information/request

### ISSUE THREAD

**Issue by njhcarroll** [tomasmcguinness/homeassistant-mixergy#29]
Hi Tomas.  I'm impressed by your integration and videos on the mixergy tank and its integration using the Eddi.  As I will struggle to get an extra spur into my airing cupboard with the tank, I'm considering the Mixergy PV diverter.  I asked for a copy of the API from moxergy to see whether I will be able to control from home assistant when it will divert PV but can't see anything in the code I was sent.  From your expert knowledge of the API, do you know if this would be possible?   Is this something you could add to your implementation?  Thanks!

**Comment by tomasmcguinness** [comment]
Hi.

I'm not sure about the Mixergy Diverter I'm afraid. I know the API will report data from the Diverter if installed, but I don't know anything about controlling it. I don't have one myself, so I can't reverse engineer the API.

Tom

**Comment by njhcarroll** [comment]
Hi Tom
Thanks for the quick reply. I’ll see if I can get someone in the tech support department to talk me through it.  If there is a possibility to control whether the PV diverter is active or not then my next challenge will be to see if Incan fork your code and make the change!  I may need some hand holding if you have time 😀
Thanks 
Nick

**Comment by tomasmcguinness** [comment]
Hi - another user of the integration has raised a similar issue #32 as they want to turn the PV divert on and off. I'm going to see if we can get this feature added in.

**Comment by njhcarroll** [comment]
Thanks for investigating Tom. Would be a great help if the feature can be added

**Comment by tomasmcguinness** [comment]
PR #34 was just merged in and release 0.7.0 should be available to download. Big thanks to @mattjgalloway *again* for adding some brilliant new features!

I'll close this issue now - do let me know if something isn't right!

**Comment by njhcarroll** [comment]
Thanks Tom.  As you say, brilliant news and great features to have added.  Thanks @mattjgalloway !
