### ISSUE TITLE
Feature: Toggle PV diverter

### ISSUE THREAD

**Issue by tdroza** [tomasmcguinness/homeassistant-mixergy#32]
In the Mixergy app in Tank Settings there's a toggle to "Use spare PV to heat tank". It would be great to be able to control this using a service in this integration. 

My use case: I'd like to be able to automate my setup for Octopus Saving Sessions and force my home battery to export, but I currently have to manually disable the Mixergy PV diverter in the app otherwise it will consume everything that I try to export.

**Comment by mattjgalloway** [comment]
I'll take a look at doing this. I've just manually worked out how the API works to control this setting, so it shouldn't be too hard to add this in to the integration now as a switch.

**Comment by tdroza** [comment]
Would it also be possible to have the integration report `clampPower`? My CT clamp seems to occasionally stop reporting data - a quick unplug/replug of the cable from the PV diverter fixes it, but it relies on me checking the app or the flashing lights on the CT sender unit. I'm not sure how often it happens but if I could access clampPower then I could have HA send me a notification as soon as it stops working

**Comment by mattjgalloway** [comment]
> Would it also be possible to have the integration report `clampPower`? 

Yes, that's part of the measurement data. I will add that as well then - good idea.

**Comment by mattjgalloway** [comment]
OK - I managed to get up to speed enough to get the start of this done:
https://github.com/mattjgalloway/homeassistant-mixergy/commit/c17e13721b9b7e159b40eeed78d8ffbcd87f5ac9

I'm not quite ready to PR this yet, as I want to also get the clamp power and I want to fix #33 as well in this stack.

**Comment by mattjgalloway** [comment]
@tdroza I've put up a PR for this issue and also #33. And bonus points I added a PR for the clamp power (#35).

**Comment by tdroza** [comment]
Awesome - Thanks for your work on this. I've been keeping an eye on the PRs - looking forward to checking this out!
