### ISSUE TITLE
Feature: Set PV charge limit

### ISSUE THREAD

**Issue by tdroza** [tomasmcguinness/homeassistant-mixergy#33]
I'd like to be able to set the charge limit that my Mixergy PV diverter will aim for. In the Mixergy app, under Tank Settings, this is listed as "PV Charge Limit" (as a percentage). This would allow me to create an automation where I increase the charge limit to allow the tank to heat more water if the solar forecast is high, or lower the PV charge limit on days with a lower solar forecast.

**Comment by mattjgalloway** [comment]
I'll also look at adding this one (like #32). It shouldn't be too hard to add. I've figured out what setting needs to change, and can control it manually via `curl`. So just need to wire it up into the integration now.

@tomasmcguinness - would you prefer this to be a sensor that can be changed, or done via a service like you've got for the target charge and target temperature setting?
