### ISSUE TITLE
virtual integrations and differentiating hubs, devices, and services.

### ISSUE THREAD

**Issue by DirkFace** [tomasmcguinness/homeassistant-mixergy#4]
Just read this on another github project & thought it was relevant,

This is not currently an issue, and probably one which is really easy to sort out - with 2022.11 versions a new property is going to be added to integration manifest files. I think from my reading that for this integration it will be "device" but I am not 100% clear on the implications.

https://developers.home-assistant.io/blog/2022/10/24/hubs-devices-services-virtual-integrations/

https://developers.home-assistant.io/docs/creating_integration_manifest/#integration-type

I think adding this to the manifest.json should be sufficient:

  "integration_type": "device",

would love someone to check and add when the next updates are done to prevent future issues

**Comment by tomasmcguinness** [comment]
I've resolved this. Thanks!
