### ISSUE TITLE
Medical Research Donation toggle not working

### ISSUE THREAD

**Issue by tdroza** [tomasmcguinness/homeassistant-mixergy#42]
Loving all the new settings in the latest release! 

The only issue I've found is that the "Medical Research Donation" toggle is always on in HA, but I have it turned off on my Mixergy. If I try to toggle it off in HA, it will revert back to on after a couple of seconds (but doesn't actually change the setting on my tank).

![image](https://github.com/tomasmcguinness/homeassistant-mixergy/assets/724245/10427ca0-e010-4603-a857-50cf265b0497)

![image](https://github.com/tomasmcguinness/homeassistant-mixergy/assets/724245/47b1dda6-1b79-4253-ae13-df4af87aaa83)

**Comment by mattjgalloway** [comment]
Sure. I might have made a slight mistake there. I thought I tested all the toggles, but perhaps messed up on that one!
