### ISSUE TITLE
Could not find a tank with the specified serial number

### ISSUE THREAD

**Issue by creednmd** [tomasmcguinness/homeassistant-mixergy#55]
Just got a new Mixergy tank and trying to set up integration with HA. Have tried logging in with correct account details and serial number, but get the error message "Could not find a tank with the specified serial number".

Know it is the correct account details, as can log in to the mixergy.io page fine, and have copy and pasted the serial from scanning the QR code on the front of the tank. (The writing on the sticker is a touch worn, and hard to read, but the QR code and text do match…)

Any idea what may be going wrong, or how I can debug the issue?

**Comment by creednmd** [comment]
So the number you think is the serial, and is referred to as the serial elsewhere, is not what you put in the setup dialog; confusing, but sorted…

**Comment by tomasmcguinness** [comment]
So, if not the serial number.....what would you call it?
