### ISSUE TITLE
Unable to download 0.8.3

### ISSUE THREAD

**Issue by Young-Grandad** [tomasmcguinness/homeassistant-mixergy#57]
I'm unable to download (via HACS) level 0.8.3 that contains the fix for the issue discovered on the latest upgrade to HA (2024.7.0). I have not been auto notified of the Mixergy update via HACS and for some reason when I access the repository entry via HACS I only see a message to support the author on Ko-fi when I expect to see the README.md.
The results are the same whether I access HA via a Windows Firefox browser or via the HA App on Apple devices,  to view the HACS repository.
I hope this makes sense.

Kind regards

**Comment by tomasmcguinness** [comment]
Sorry, that's out of my control I'm afraid. When I open the Integration via my HomeAssistant, it shows the 0.8.3 version.

![image](https://github.com/tomasmcguinness/homeassistant-mixergy/assets/302741/03ee2e4b-1cb9-46ff-8748-1cd48984eaba)

Several users in issues #56 have reported success.

Perhaps raise an issue with HACS? Sorry I can't be more help.

**Comment by Young-Grandad** [comment]
Thanks for the hint. As it turns out I was able to download the fix in 0.8.3 after I updated HA core to 2024.7.1.
