### ISSUE TITLE
Missing entities? 

### ISSUE THREAD

**Issue by Heretik999666** [tomasmcguinness/homeassistant-mixergy#58]
Hi there, 
Hope you can help - I hadn't actually completed these dashboards which is why they are in several bits, but I think this happened whilst updating; I seem to have lost a lot of entities? I was hoping to be able to run an automation where i set it to use electric as a source and then kick off hearing the tank to a set charge and these options no longer seem to be available? Any ideas or suggestions welcome, thanks :)

![image](https://github.com/tomasmcguinness/homeassistant-mixergy/assets/59658709/a84ad4cf-3d47-4457-b581-cd305a29dfd3)

**Comment by jeffjsmith33** [comment]
My Mixergy entities have also gone unavailable after an update that I took yesterday.  It has been working fine, but I fear something got broken perhaps.  I tried re-installing, but to no avail.

**Comment by tomasmcguinness** [comment]
I think the entity names have changed e.g. you reference `sensor.target_charge`, but this is now called `sensor.mixergy_target_charge`. 

Check the integration itself to be sure all the entities are present.

I don't remember when I did that, so sorry about that!

**Comment by jeffjsmith33** [comment]
I removed and downloaded the integration again, and that seems to have cleared up my issues.  I am guessing that there was some corruption over the update.

Thanks for your work, and your reply - I really appreciate it.  And btw, my entity is still sensor.target_charge

**Comment by Heretik666999** [comment]
Hi there, I can report this is all working as expected for me again too thank you. I did a few things that may have helped, namely updating HA and my NAS drive, which required suspening and restarting my HA VM. All entities are back now - so all good thanks. Switch it off and on again :)

**Comment by tomasmcguinness** [comment]
Great!
