### ISSUE TITLE
Feature request: Set Default Heat Source

### ISSUE THREAD

**Issue by njhcarroll** [tomasmcguinness/homeassistant-mixergy#59]
Hi Tomas
I have finally taken the plunge and installed a Mixergy tank.  It is working well and I can see savings already and your excellent HA integration offers great potential (if I could have the following :) )

I am on the Agile Octopus tariff and it would be great to be able to automatically kick the tank into a boost on electricity when there is a plunge price period or on the rare occasions when we might want to boost the capacity be able to have it select to charge on electricity if the price per Kw is less than gas which is the default heating source.

So the request is to have a select entity (and service to change it) which offers "Indirect", "Electric", "Heat pump" which could be changed by an automation before requesting a charge.  Another automation could then switch it back to the default on completion. 

It looks like this could be done in the schedule endpoint section of the API.  Sadly, I don't have the skills to safely tinker with your code!

I would really appreciate it if you could update your code if I am right that feature could be added.

Many thanks.  Nick

**Comment by tomasmcguinness** [comment]
In the works!

![image](https://github.com/user-attachments/assets/08955fc3-ca44-49eb-a572-1fb703d482fc)

**Comment by tomasmcguinness** [comment]
Available in v0.9.0

Please give it a try!

**Comment by njhcarroll** [comment]
Hi TomasIt works!  Thank you for your time on this.FYI, I was getting a bunch of warnings in the logs on the lines of “ Detected that custom integration 'mixergy' calls async_forward_entry_setup for integration, mixergy with title: ”They seem to have disappeared post the update so I assume you have been able to fix this as well?  Again, many thanks for your time adding this functionality.  Now I have to looking into automations to use the new service!Best regardsNickOn 20 Oct 2024, at 10:05, Tomas McGuinness ***@***.***> wrote:﻿
Available in v0.9.0
Please give it a try!

**Comment by tomasmcguinness** [comment]
I fixed those warnings as part of the same update. It was logged in ticket #62.

If you'd like to buy a coffee or beer by way of thanks, all donations are greatly received :) https://ko-fi.com/tomasmcguinness

Do let me know if you run into any issues!

**Comment by njhcarroll** [comment]
Brilliant.  A caffeine fix donation has been made 😀Best regardsNickOn 20 Oct 2024, at 21:11, Tomas McGuinness ***@***.***> wrote:﻿
I fixed those warnings as part of the same update. It was logged in ticket #62.
If you'd like to buy a coffee or beer by way of thanks, all donations are greatly received :) https://ko-fi.com/tomasmcguinness
Do let me know if you run into any issues!

**Comment by tomasmcguinness** [comment]
Thanks you! Very generous!!!
