### ISSUE TITLE
Breaking changes for Home Assistant 2025.1 release

### ISSUE THREAD

**Issue by Heretik666999** [tomasmcguinness/homeassistant-mixergy#62]
Hi there, I noticed the below in my logs today; looks like there will be some breaking changes in the upcoming Home Assistant 2025.1 release - suggested I report - so here we are! Hoping you can fix :)
Thanks

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:155
First occurred: 19:29:23 (13 occurrences)
Last logged: 19:29:53

Detected code that calls async_forward_entry_setup for integration mixergy with title: MX009028 and entry_id: 01J7PZS3CFFRB4S4B5NZA06TN4, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Detected code that calls async_forward_entry_setup for integration hon with title: Myemail@gmail.com and entry_id: 01JA2Q2J7164JJ8NHBA4ASF0WA, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by tomasmcguinness** [comment]
Thanks for bringing that to my attention!

**Comment by tomasmcguinness** [comment]
Should now be resolved by version v0.9.0

**Comment by Heretik666999** [comment]
You're welcome and thanks for the intergration! Very useful :) I kick off heating my tank when my solar battery hits 100% as well as a few other conditions, which along with saving a lot of money, has been really useful!
