### ISSUE TITLE
Use local network

### ISSUE THREAD

**Issue by craigbeat** [tomasmcguinness/homeassistant-mixergy#7]
Is it possible for this to use the local network to control the tank, or must it use the Mixergy Cloud?

I've had no internet for nearly 5 days due to a fault, and it would be very useful to control without going to the garage.

Thank you.

**Comment by tomasmcguinness** [comment]
Hi. Unfortunately there is no local API that I'm aware of. I've been asking them every 6 to 12 months, but beyond "this is on our roadmap" nothing has happened on this front. I'm seriously thinking of a little hardware unit that would make the control unit wireless!

**Comment by craigbeat** [comment]
No worries, and that's a real shame as it looks like I won't be back online until the 27th. A little hardware unit would be a good compromise!
